FROM debian:bookworm
LABEL maintainer "lily@tacticalchihuahua.lol"
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -yq upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get -yq install wget apt-transport-https gnupg curl libssl-dev git python3 build-essential tor
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash -
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
ENV GRANAX_USE_SYSTEM_TOR="1"
RUN git clone https://github.com/lilyannehall/dusk /root/dusk; \
    cd /root/dusk && npm install --unsafe-perm --production
VOLUME ["/root/.config/dusk"]
EXPOSE 5274
EXPOSE 5275
ENV kadence_NodeListenAddress="0.0.0.0"
ENV kadence_ControlSockEnabled="0"
ENV kadence_ControlPortEnabled="1"
ENV kadence_TestNetworkEnabled="1"
ENV kadence_DaemonPidFilePath="/tmp/dusk.pid"
ENTRYPOINT ["/root/dusk/bin/dusk.js"]
CMD []
